name: publish

# Only run this on push since that is when
# the containers should be built and pushed
# to docker hub.
on: [ push ]

env:
  ENERGYPLUS_VERSION: 25.1.0
  ENERGYPLUS_SHA: 68a4a7c774
  ENERGYPLUS_INSTALL_VERSION: 25-1-0
  ENERGYPLUS_TAG: v25.1.0
  UBUNTU_BASE: 22.04

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: test and build
        shell: bash
        run: |
          docker build -t energyplus:latest \
          --build-arg ENERGYPLUS_VERSION=$ENERGYPLUS_VERSION \
          --build-arg ENERGYPLUS_SHA=$ENERGYPLUS_SHA \
          --build-arg ENERGYPLUS_INSTALL_VERSION=$ENERGYPLUS_INSTALL_VERSION \
          --build-arg ENERGYPLUS_TAG=$ENERGYPLUS_TAG \
          --build-arg UBUNTU_BASE=$UBUNTU_BASE .
          docker run energyplus:latest EnergyPlus --version
          # Run some tests including Python EMS
          docker run energyplus:latest /bin/bash -c "cd /var/simdata/energyplus && EnergyPlus -D ../1ZoneUncontrolled.idf"
          docker run energyplus:latest /bin/bash -c "cd /var/simdata/energyplus && EnergyPlus -D ../PythonPluginCustomOutputVariable.idf"
      - name: deploy docker
        if: ${{ success() }} &&
          github.ref == 'refs/heads/main' ||
          github.ref == 'refs/heads/develop'
        shell: bash
        run: ./deploy_docker.sh
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
