name: publish

# Only run this on push since that is when 
# the containers should be built and pushed 
# to docker hub.
on: [push]

env:
  ENERGYPLUS_VERSION: 9.6.0
  ENERGYPLUS_SHA: 4b123cf80f
  ENERGYPLUS_INSTALL_VERSION: 9-6-0
  ENERGYPLUS_TAG: v9.6.0_PlusSpaceFix1

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: test and build
      shell: bash
      run: |
          docker build -t energyplus:latest \
          --build-arg ENERGYPLUS_VERSION=$ENERGYPLUS_VERSION \
          --build-arg ENERGYPLUS_SHA=$ENERGYPLUS_SHA \
          --build-arg ENERGYPLUS_INSTALL_VERSION=$ENERGYPLUS_INSTALL_VERSION \
          --build-arg ENERGYPLUS_TAG=$ENERGYPLUS_TAG .
          docker run energyplus:latest EnergyPlus --version
          # Run some tests including Python EMS
          docker run energyplus:latest /bin/bash -c "cd /var/simdata/energyplus && EnergyPlus -D ../1ZoneUncontrolled.idf"
          docker run energyplus:latest /bin/bash -c "cd /var/simdata/energyplus && EnergyPlus -D ../PythonPluginCustomOutputVariable.idf"
    - name: deploy docker
      if: ${{ success() }} &&
         github.ref == 'refs/heads/main' ||
         github.ref == 'refs/heads/develop'
      shell: bash
      run: ./deploy_docker.sh
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
